#!/usr/bin/env bash
# update-skills-references.sh
#
# Reads SKILL.md frontmatter (name, description) from every skill in skills/
# and rebuilds the Skills Reference table in README.md between the
# <!-- SKILLS_REFERENCE_START --> and <!-- SKILLS_REFERENCE_END --> markers.
#
# Usage:
#   ./misc/update-skills-references.sh          # run from repo root
#   ./misc/update-skills-references.sh --dry-run # preview without writing

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
README="$REPO_ROOT/README.md"
SKILLS_DIR="$REPO_ROOT/skills"
DRY_RUN=false

if [[ "${1:-}" == "--dry-run" ]]; then
  DRY_RUN=true
fi

# --- Parse frontmatter from a SKILL.md file ---
# Extracts the value for a given key from YAML frontmatter (between --- delimiters)
parse_frontmatter() {
  local file="$1"
  local key="$2"
  # Read between first and second --- lines, then grab the key
  awk -v key="$key" '
    /^---$/ { block++; next }
    block == 1 && $0 ~ "^" key ":" {
      sub("^" key ":[ ]*", "")
      print
      exit
    }
    block >= 2 { exit }
  ' "$file"
}

# --- Build the new table ---
build_table() {
  echo '## Skills Reference'
  echo ''
  echo '> _This table is auto-generated by [`misc/update-skills-references.sh`](misc/update-skills-references.sh). Do not edit manually._'
  echo ''
  echo '| Skill | What It Covers |'
  echo '|-------|---------------|'

  for skill_dir in "$SKILLS_DIR"/*/; do
    local skill_md="$skill_dir/SKILL.md"
    if [[ ! -f "$skill_md" ]]; then
      continue
    fi

    local name
    local description
    name="$(parse_frontmatter "$skill_md" "name")"
    description="$(parse_frontmatter "$skill_md" "description")"

    # Skip if we couldn't parse name
    if [[ -z "$name" ]]; then
      echo "  WARNING: No name found in $skill_md" >&2
      continue
    fi

    # Use description, or fallback
    if [[ -z "$description" ]]; then
      description="_(no description in frontmatter)_"
    fi

    local folder_name
    folder_name="$(basename "$skill_dir")"
    echo "| **[$name](skills/$folder_name/)** | $description |"
  done
}

# --- Replace the section in README.md ---
START_MARKER='<!-- SKILLS_REFERENCE_START -->'
END_MARKER='<!-- SKILLS_REFERENCE_END -->'

if ! grep -q "$START_MARKER" "$README"; then
  echo "ERROR: Could not find $START_MARKER in $README" >&2
  echo "Add the markers around the Skills Reference section first." >&2
  exit 1
fi

if ! grep -q "$END_MARKER" "$README"; then
  echo "ERROR: Could not find $END_MARKER in $README" >&2
  exit 1
fi

# Build the new content
NEW_SECTION="$(build_table)"

if $DRY_RUN; then
  echo "=== DRY RUN — would replace Skills Reference with: ==="
  echo ""
  echo "$START_MARKER"
  echo "$NEW_SECTION"
  echo "$END_MARKER"
  echo ""
  echo "=== No changes written ==="
  exit 0
fi

# Use awk to replace everything between the markers (inclusive)
awk -v start="$START_MARKER" -v end="$END_MARKER" -v new_section="$NEW_SECTION" '
  $0 == start {
    print start
    print new_section
    skip = 1
    next
  }
  $0 == end {
    print end
    skip = 0
    next
  }
  !skip { print }
' "$README" > "$README.tmp"

mv "$README.tmp" "$README"

echo "✅ Skills Reference table updated in README.md"
echo "   Skills found:"
for skill_dir in "$SKILLS_DIR"/*/; do
  if [[ -f "$skill_dir/SKILL.md" ]]; then
    echo "   - $(basename "$skill_dir")"
  fi
done
