#!/usr/bin/env bash
# update-pages.sh
#
# Generates Docusaurus wrappers for skills/*/SKILL.md and
# steering/workflows/*.md under misc/website/docs/, plus the
# misc/website/static/manifests/skills.json manifest consumed by the
# homepage SkillGrid.
#
# Inputs (sources of truth):
#   skills/*/SKILL.md
#   steering/workflows/*.md
#
# Outputs (regenerated; tracked in git):
#   misc/website/docs/skills/<name>.md      one wrapper per skill
#   misc/website/docs/skills/index.md       card grid (overwritten each run)
#   misc/website/docs/steering/<name>.md    one wrapper per workflow
#   misc/website/static/manifests/skills.json
#
# misc/website/docs/steering/index.md is HAND-WRITTEN and never touched.
#
# Usage:
#   ./misc/update-pages.sh              # regenerate in place
#   ./misc/update-pages.sh --check      # fail if generated artifacts are stale
#   ./misc/update-pages.sh --dry-run    # print what would be written; no edits
#
# --check is what the `docs-sync` CI job runs alongside
# update-all-references.sh: regenerate in place, then `git diff --exit-code`
# on the output paths. Non-zero exit means someone edited a wrapper by hand
# or added/edited a skill/workflow without running this script.
# Fix: `./misc/update-pages.sh && git add … && commit`.

set -euo pipefail

MODE="run"
if [[ "${1:-}" == "--check" ]]; then
  MODE="check"
elif [[ "${1:-}" == "--dry-run" ]]; then
  MODE="dry-run"
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

SKILLS_DIR="$REPO_ROOT/skills"
WORKFLOWS_DIR="$REPO_ROOT/steering/workflows"
SKILLS_OUT="$REPO_ROOT/misc/website/docs/skills"
STEERING_OUT="$REPO_ROOT/misc/website/docs/steering"
MANIFEST="$REPO_ROOT/misc/website/static/manifests/skills.json"

GH_BASE="https://github.com/aws-samples/sample-apex-skills/blob/main"

# Files this script may touch — the blast radius of --check.
TOUCHED_PATHS=(
  "misc/website/docs/skills"
  "misc/website/docs/steering"
  "misc/website/static/manifests"
)

# --- Parse one frontmatter key from a markdown file -----------------------
# Mirrors parse_frontmatter() in update-skills-references.sh so both scripts
# accept the same input shape. Single-line values only; quoted (single or
# double) values are unwrapped.
parse_frontmatter() {
  local file="$1"
  local key="$2"
  awk -v key="$key" '
    /^---$/ { block++; next }
    block == 1 && $0 ~ "^" key ":" {
      sub("^" key ":[ ]*", "")
      sub("^\"", ""); sub("\"$", "")
      sub("^'\''", ""); sub("'\''$", "")
      print
      exit
    }
    block >= 2 { exit }
  ' "$file"
}

# --- Strip leading YAML frontmatter from a markdown file ------------------
# Files without frontmatter are passed through unchanged.
strip_frontmatter() {
  local file="$1"
  awk '
    BEGIN { mode = "preamble" }
    mode == "preamble" && NR == 1 && /^---[[:space:]]*$/ { mode = "in_fm"; next }
    mode == "preamble" { mode = "body"; print; next }
    mode == "in_fm" && /^---[[:space:]]*$/ { mode = "body"; next }
    mode == "in_fm" { next }
    mode == "body" { print }
  ' "$file"
}

# --- YAML-safe scalar via JSON encoding (JSON is a subset of YAML) --------
# Handles embedded quotes, colons, em dashes, etc. without hand-rolling
# YAML escape rules.
yaml_scalar() {
  python3 -c 'import json, sys; print(json.dumps(sys.argv[1], ensure_ascii=False))' "$1"
}

# --- Build a per-skill wrapper to stdout ----------------------------------
build_skill_wrapper() {
  local folder="$1"
  local name="$2"
  local description="$3"
  local skill_md="$SKILLS_DIR/$folder/SKILL.md"
  local desc_yaml
  desc_yaml="$(yaml_scalar "$description")"

  cat <<EOF
---
title: $name
description: $desc_yaml
custom_edit_url: $GH_BASE/skills/$folder/SKILL.md
format: md
---

:::info[Source]
This page is generated from [skills/$folder/SKILL.md]($GH_BASE/skills/$folder/SKILL.md). Edit the source, not this page.
:::

EOF
  strip_frontmatter "$skill_md"
}

# --- Build a per-workflow wrapper to stdout -------------------------------
build_workflow_wrapper() {
  local file="$1"     # path to steering/workflows/foo.md
  local name="$2"
  local description="$3"
  local base
  base="$(basename "$file")"
  local desc_yaml
  desc_yaml="$(yaml_scalar "$description")"

  cat <<EOF
---
title: $name
description: $desc_yaml
custom_edit_url: $GH_BASE/steering/workflows/$base
format: md
---

:::info[Source]
This page is generated from [steering/workflows/$base]($GH_BASE/steering/workflows/$base). Edit the source, not this page.
:::

EOF
  strip_frontmatter "$file"
}

# --- Build skills/index.md card grid to stdout ----------------------------
build_skills_index() {
  cat <<'EOF'
---
sidebar_position: 1
title: Skills
---

# Skills

> _This page is auto-generated by [`misc/update-pages.sh`](https://github.com/aws-samples/sample-apex-skills/blob/main/misc/update-pages.sh). Do not edit manually._

EOF
  for skill_dir in "$SKILLS_DIR"/*/; do
    local skill_md="$skill_dir/SKILL.md"
    [[ -f "$skill_md" ]] || continue
    local folder name description
    folder="$(basename "$skill_dir")"
    name="$(parse_frontmatter "$skill_md" "name")"
    description="$(parse_frontmatter "$skill_md" "description")"
    [[ -n "$name" ]] || continue
    [[ -n "$description" ]] || description="_(no description in frontmatter)_"
    echo "## [$name](./$folder.md)"
    echo ""
    echo "$description"
    echo ""
  done
}

# --- Build skills.json manifest to stdout ---------------------------------
build_manifest() {
  python3 - "$SKILLS_DIR" <<'PY'
import json, os, re, sys

skills_dir = sys.argv[1]


def parse_fm(path):
    with open(path, encoding="utf-8") as f:
        lines = f.read().splitlines()
    if not lines or lines[0].strip() != "---":
        return {}
    fm = {}
    for line in lines[1:]:
        if line.strip() == "---":
            break
        m = re.match(r'^([A-Za-z_][A-Za-z0-9_-]*):\s*(.*)$', line)
        if not m:
            continue
        k, v = m.group(1), m.group(2).strip()
        if (v.startswith('"') and v.endswith('"')) or (
            v.startswith("'") and v.endswith("'")
        ):
            v = v[1:-1]
        fm[k] = v
    return fm


out = []
for entry in sorted(os.listdir(skills_dir)):
    sd = os.path.join(skills_dir, entry)
    sm = os.path.join(sd, "SKILL.md")
    if not os.path.isfile(sm):
        continue
    fm = parse_fm(sm)
    name = fm.get("name") or entry
    out.append({
        "name": name,
        "description": fm.get("description", ""),
        "path": f"/docs/skills/{entry}",
    })

print(json.dumps(out, indent=2, ensure_ascii=False))
PY
}

# --- Remove wrappers for skills/workflows that no longer exist ------------
cleanup_stale() {
  local dir="$1"
  shift
  local -a keep=("$@")
  [[ -d "$dir" ]] || return 0
  shopt -s nullglob
  for existing in "$dir"/*.md; do
    local base
    base="$(basename "$existing")"
    local should_keep=false
    for k in "${keep[@]}"; do
      if [[ "$base" == "$k" ]]; then
        should_keep=true
        break
      fi
    done
    $should_keep || rm "$existing"
  done
  shopt -u nullglob
}

# =========================================================================
# Generate
# =========================================================================

if [[ "$MODE" == "dry-run" ]]; then
  echo "=== DRY RUN — would write the following ==="
fi

declare -a EXPECTED_SKILL_FILES=("index.md")
declare -a EXPECTED_STEERING_FILES=("index.md")  # hand-written index is preserved

# --- Per-skill wrappers ---
for skill_dir in "$SKILLS_DIR"/*/; do
  skill_md="$skill_dir/SKILL.md"
  [[ -f "$skill_md" ]] || continue

  folder="$(basename "$skill_dir")"
  name="$(parse_frontmatter "$skill_md" "name")"
  description="$(parse_frontmatter "$skill_md" "description")"
  if [[ -z "$name" ]]; then
    echo "  WARNING: No name in $skill_md — skipping" >&2
    continue
  fi

  out_file="$SKILLS_OUT/$folder.md"
  EXPECTED_SKILL_FILES+=("$folder.md")

  if [[ "$MODE" == "dry-run" ]]; then
    echo "--- $out_file ---"
    build_skill_wrapper "$folder" "$name" "$description"
    echo ""
  else
    mkdir -p "$SKILLS_OUT"
    build_skill_wrapper "$folder" "$name" "$description" > "$out_file.tmp"
    mv "$out_file.tmp" "$out_file"
  fi
done

# --- Skills index (card grid) ---
if [[ "$MODE" == "dry-run" ]]; then
  echo "--- $SKILLS_OUT/index.md ---"
  build_skills_index
  echo ""
else
  mkdir -p "$SKILLS_OUT"
  build_skills_index > "$SKILLS_OUT/index.md.tmp"
  mv "$SKILLS_OUT/index.md.tmp" "$SKILLS_OUT/index.md"
fi

# --- Per-workflow wrappers ---
if [[ -d "$WORKFLOWS_DIR" ]]; then
  shopt -s nullglob
  for wf_file in "$WORKFLOWS_DIR"/*.md; do
    name="$(parse_frontmatter "$wf_file" "name")"
    description="$(parse_frontmatter "$wf_file" "description")"
    if [[ -z "$name" ]]; then
      echo "  WARNING: No name in $wf_file — skipping" >&2
      continue
    fi

    base="$(basename "$wf_file")"
    out_file="$STEERING_OUT/$base"
    EXPECTED_STEERING_FILES+=("$base")

    if [[ "$MODE" == "dry-run" ]]; then
      echo "--- $out_file ---"
      build_workflow_wrapper "$wf_file" "$name" "$description"
      echo ""
    else
      mkdir -p "$STEERING_OUT"
      build_workflow_wrapper "$wf_file" "$name" "$description" > "$out_file.tmp"
      mv "$out_file.tmp" "$out_file"
    fi
  done
  shopt -u nullglob
fi

# --- Manifest ---
if [[ "$MODE" == "dry-run" ]]; then
  echo "--- $MANIFEST ---"
  build_manifest
  echo ""
else
  mkdir -p "$(dirname "$MANIFEST")"
  build_manifest > "$MANIFEST.tmp"
  mv "$MANIFEST.tmp" "$MANIFEST"
fi

# --- Stale-wrapper cleanup (only in real-write mode) ---
if [[ "$MODE" != "dry-run" ]]; then
  cleanup_stale "$SKILLS_OUT" "${EXPECTED_SKILL_FILES[@]}"
  cleanup_stale "$STEERING_OUT" "${EXPECTED_STEERING_FILES[@]}"
fi

# --- Dry-run exits here ---
if [[ "$MODE" == "dry-run" ]]; then
  echo "=== No changes written ==="
  exit 0
fi

# --- --check: regen happened in place above; now diff against committed state
if [[ "$MODE" == "check" ]]; then
  diff_dirty=false
  if ! git diff --quiet -- "${TOUCHED_PATHS[@]}"; then
    diff_dirty=true
  fi
  untracked="$(git ls-files --others --exclude-standard -- "${TOUCHED_PATHS[@]}")"

  if $diff_dirty || [[ -n "$untracked" ]]; then
    echo ""
    echo "ERROR: Docusaurus wrappers / manifest are stale."
    if $diff_dirty; then
      echo ""
      echo "Diff:"
      git --no-pager diff -- "${TOUCHED_PATHS[@]}"
    fi
    if [[ -n "$untracked" ]]; then
      echo ""
      echo "Untracked (newly generated) files:"
      printf '  %s\n' $untracked
    fi
    echo ""
    echo "Fix: run ./misc/update-pages.sh locally, commit the result."
    exit 1
  fi
  echo "✓ Docusaurus wrappers + manifest are in sync with skills/ and steering/"
  exit 0
fi

# --- Run mode summary ---
echo "✅ Generated Docusaurus wrappers and manifest:"
echo "   Skills:   $(find "$SKILLS_OUT" -maxdepth 1 -name '*.md' | wc -l) files in misc/website/docs/skills/"
echo "   Steering: $(find "$STEERING_OUT" -maxdepth 1 -name '*.md' | wc -l) files in misc/website/docs/steering/"
echo "   Manifest: misc/website/static/manifests/skills.json"
