# =============================================================================
# SKELETON — Replatform environment (ECS on EC2, containerize-as-is)
#
# Copy this directory, then fill the values the assessment settled. Every
# variable below is either supplied from a traceable source or left as a
# required input; none carries a fabricated default.
#
# Generated by the ecs-modernize skill, module 9b
# (references/replatform-environment-build.md).
# =============================================================================

variable "region" {
  description = "AWS region for the target environment."
  type        = string
}

variable "name_prefix" {
  description = "Prefix for every resource name. Keep it short — ALB names cap at 32 characters."
  type        = string
}

# --- image -------------------------------------------------------------------

variable "image_uri" {
  description = <<-EOT
    Full ECR image URI including the tag, from the containerization execution
    push result. When the push has not run, leave this unset and supply it at
    apply time — do not substitute `:latest`, which would apply the wrong image
    silently.
  EOT
  type        = string
}

# --- application contract (from the containerization artifact) ---------------

variable "container_port" {
  description = "Port the container listens on, from the Dockerfile EXPOSE / task-definition inputs."
  type        = number
}

variable "health_check_path" {
  description = <<-EOT
    ALB health check path. Use the application's own health endpoint when
    Source_Analysis identified one; otherwise the application root, and record
    the substitution.
  EOT
  type        = string
}

# --- sizing (from the capacity derivation) -----------------------------------
#
# The Replatform path derives these from the CURRENT environment rather than
# from a cloud sizing exercise: the unmodified application's appetite does not
# change by being containerized. Supply them from the live environment; there
# are deliberately no defaults, because a guessed number here silently
# mis-sizes the fleet.

variable "task_cpu" {
  description = "CPU units reserved per task (1024 = 1 vCPU), from the current per-instance sizing."
  type        = number
}

variable "task_memory" {
  description = <<-EOT
    Memory (MiB) reserved per task. This is a hard reservation on EC2: it must
    fit inside the instance's allocatable memory or tasks never place.
  EOT
  type        = number
}

variable "desired_count" {
  description = <<-EOT
    Fixed number of tasks. Derivation: parity with the number of application
    instances serving the workload today, which preserves the concurrency and
    failure characteristics operations already understands. No scaling policy
    is attached — the static configuration is the point of this path.
  EOT
  type        = number
}

variable "instance_type" {
  description = <<-EOT
    Container instance type, from the capacity derivation: per-task footprint x
    desired_count / instance capacity, plus N+1 headroom across >= 2 AZs.
  EOT
  type        = string
}

variable "instance_count" {
  description = <<-EOT
    Fixed number of container instances (ASG min = max = this). Includes the
    N+1 spare so a single instance failure or a rolling task replacement does
    not leave the service below desired_count.
  EOT
  type        = number
}

# --- conditioned on assessment findings --------------------------------------

variable "session_affinity_required" {
  description = <<-EOT
    Enable ALB target-group stickiness. Set true ONLY when blocker detection
    reported an in_process_session finding, and cite the blocker id where this
    value is supplied. Affinity keeps a user on one task but does NOT survive
    that task's replacement — sessions are still lost then.

    When the session state could not be established (assessment skipped, or
    server-side session persistence lives outside the source tree), set true as
    the fail-safe and record that it is provisional pending user confirmation.
  EOT
  type        = bool
}

# --- networking --------------------------------------------------------------
#
# Two modes, because both are ordinary for a migration:
#
#   * CREATE  — the target network does not exist yet. Typical for on-premises
#               and VMware migrations, and for any move into a fresh account or
#               a landing-zone spoke. Leave vpc_id null and the skeleton builds
#               a VPC, subnets, IGW, and routes.
#   * REUSE   — an existing VPC receives the workload. Typical when the source
#               already runs on EC2 in the same account, or when a landing zone
#               dictates the network. Supply vpc_id and subnet_ids.
#
# Neither is the default: the mode is a decision, so state which one the user
# chose and why. Do not assume an existing VPC — a migration from outside AWS
# has none.

variable "vpc_id" {
  description = <<-EOT
    Existing VPC to deploy into (REUSE mode). Leave null to have this skeleton
    create the network (CREATE mode) — the normal case for an on-premises or
    VMware migration, where no target VPC exists yet.
  EOT
  type        = string
  default     = null
}

variable "subnet_ids" {
  description = <<-EOT
    Subnets for the ALB and the container instances in REUSE mode — at least
    two, in different AZs, since the capacity plan spreads the fixed fleet
    across AZs. Ignored in CREATE mode.
  EOT
  type        = list(string)
  default     = []

  validation {
    condition     = length(var.subnet_ids) == 0 || length(var.subnet_ids) >= 2
    error_message = "REUSE mode needs at least two subnets in different AZs; leave the list empty for CREATE mode."
  }
}

variable "vpc_cidr" {
  description = <<-EOT
    CIDR for the VPC this skeleton creates in CREATE mode. Choose a range that
    does not overlap the source environment's network — an overlap breaks the
    hybrid connectivity a migration usually needs during cutover.
  EOT
  type        = string
  default     = "10.20.0.0/16"
}

variable "ingress_cidr" {
  description = <<-EOT
    CIDR permitted to reach the ALB. There is no default: opening a listener to
    the internet is the user's decision to state explicitly, not a value to
    inherit silently.
  EOT
  type        = string
}

variable "assign_public_ip" {
  description = <<-EOT
    Whether container instances get public IPs. **REUSE mode only** — CREATE mode
    always assigns them, because it builds public subnets with no NAT gateway and
    an instance there without a public IP has no internet path at all.

    In REUSE mode this must match the subnets you supplied: `true` for public
    subnets, or `false` for private subnets that reach ECR and the ECS control
    plane through a NAT route or VPC endpoints. Getting it wrong does not fail
    the apply — instances simply never join the cluster.
  EOT
  type        = bool
  default     = false
}

# --- operations --------------------------------------------------------------

variable "log_retention_days" {
  description = <<-EOT
    CloudWatch Logs retention. An unset retention means "never expire", which
    is a cost surprise rather than a sensible default — so this is explicit.
  EOT
  type        = number
  default     = 30
}

variable "enable_execute_command" {
  description = <<-EOT
    Enable ECS Exec. The Replatform path's operational-procedures table lists it
    as the replacement for host-login diagnostics, and it adds a task role
    granting only the SSM message-channel actions.

    It defaults to OFF because this skeleton configures no
    execute_command_configuration — no audit log, no KMS key — so enabling it
    hands out an unaudited interactive shell inside the task. Turn it on
    deliberately, and for anything beyond a short-lived migration cutover pair it
    with cluster-level Exec logging (`ecs-security` covers the shape).
  EOT
  type        = bool
  default     = false
}

variable "iam_role_path" {
  description = <<-EOT
    IAM path for the roles and instance profile this skeleton creates. It exists
    so the operator's own IAM permissions can be resource-scoped to
    `arn:aws:iam::*:role/<path>*` — role names derive from name_prefix and are
    therefore unpredictable, so the path is the only stable handle. Must begin and
    end with "/".
  EOT
  type        = string
  default     = "/ecs-modernize/"

  validation {
    condition     = can(regex("^/.*/$", var.iam_role_path))
    error_message = "iam_role_path must begin and end with a forward slash, e.g. /ecs-modernize/."
  }
}

variable "health_check_grace_period_seconds" {
  description = <<-EOT
    How long the service ignores ALB health checks after a task starts. The
    Replatform path runs an unmodified application, so slow starts are the norm
    rather than a bug; too small a grace period makes ECS kill tasks that are
    still warming up. Raise it to comfortably exceed the observed startup time.
  EOT
  type        = number
  default     = 120
}

variable "log_driver_mode" {
  description = <<-EOT
    awslogs delivery mode, set explicitly rather than left to the default. Since
    2025-06-25 an unset mode means non-blocking, which silently drops lines once
    its buffer fills — bad during the steady-state verification this path ends
    with, where the logs are the diagnosis.

    non-blocking is still the default here: blocking backs pressure up into the
    application's stdout writes and can hang a container. Choose blocking only
    when complete logs matter more than task availability.
  EOT
  type        = string
  default     = "non-blocking"

  validation {
    condition     = contains(["non-blocking", "blocking"], var.log_driver_mode)
    error_message = "log_driver_mode must be non-blocking or blocking."
  }
}

variable "log_max_buffer_size" {
  description = <<-EOT
    Buffer for non-blocking mode. The driver's own default is 1 MiB, which a
    chatty legacy application can overrun in seconds; this widens it. Ignored in
    blocking mode, where the option is not valid.
  EOT
  type        = string
  default     = "25m"
}

variable "tags" {
  description = "Tags applied to every resource that supports them."
  type        = map(string)
  default     = {}
}
